[[redirects]]
  from = "/tux-thinkpad.glb"
  to = "https://michaelradu.netlify.app/tux-thinkpad.glb"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://mihairadu.cf"
